"""HTML preview generator for threads."""

import base64
from datetime import datetime
from pathlib import Path

from vibesignal.models import Thread


class HTMLPreview:
    """Generate HTML preview of thread that looks like Twitter."""

    def generate(self, thread: Thread, workspace: Path, output_path: Path) -> Path:
        """Generate HTML preview file.

        Args:
            thread: Thread to preview
            workspace: Workspace containing images
            output_path: Path to save HTML file

        Returns:
            Path: Path to generated HTML file
        """
        html = self._generate_html(thread, workspace)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)

        return output_path

    def _generate_html(self, thread: Thread, workspace: Path) -> str:
        """Generate HTML content.

        Args:
            thread: Thread to preview
            workspace: Workspace containing images

        Returns:
            str: HTML content
        """
        tweets_html = []

        for i, tweet in enumerate(thread.tweets):
            is_reply = i > 0
            tweet_html = self._generate_tweet_html(tweet, workspace, is_reply, len(thread.tweets))
            tweets_html.append(tweet_html)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thread Preview - {thread.hook[:50]}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🧵 Thread Preview</h1>
            <div class="stats">
                <span class="stat"><strong>{len(thread.tweets)}</strong> tweets</span>
                <span class="stat"><strong>{thread.metadata.total_images}</strong> images</span>
                <span class="stat">Generated by <strong>VibeSignal</strong></span>
            </div>
        </div>

        <div class="hook-section">
            <div class="hook-label">🎣 Thread Hook</div>
            <div class="hook-text">{self._escape_html(thread.hook)}</div>
        </div>

        <div class="thread-container">
            {''.join(tweets_html)}
        </div>

        {self._generate_cta_html(thread) if thread.call_to_action else ''}

        <div class="footer">
            <p><strong>Note:</strong> This is a preview. Images and formatting may differ slightly on actual Twitter.</p>
            <p class="source">Source: {self._escape_html(thread.metadata.source_notebook)}</p>
        </div>
    </div>
</body>
</html>"""

    def _generate_tweet_html(self, tweet, workspace: Path, is_reply: bool, total_tweets: int) -> str:
        """Generate HTML for a single tweet.

        Args:
            tweet: Tweet to render
            workspace: Workspace for images
            is_reply: Whether this is a reply tweet
            total_tweets: Total number of tweets in thread

        Returns:
            str: HTML for tweet
        """
        # Reply indicator
        reply_html = ''
        if is_reply:
            reply_html = '<div class="reply-line"></div><div class="reply-label">↳ Replying</div>'

        # Image HTML
        image_html = ''
        if tweet.image_filename:
            image_path = workspace / "images" / tweet.image_filename
            if image_path.exists():
                # Encode image as base64 for embedding
                with open(image_path, 'rb') as f:
                    image_data = base64.b64encode(f.read()).decode('utf-8')
                    # Determine MIME type
                    ext = image_path.suffix.lower()
                    mime_type = {
                        '.png': 'image/png',
                        '.jpg': 'image/jpeg',
                        '.jpeg': 'image/jpeg',
                        '.gif': 'image/gif',
                    }.get(ext, 'image/png')

                    image_html = f'''
                    <div class="tweet-image">
                        <img src="data:{mime_type};base64,{image_data}" alt="Tweet image">
                    </div>
                    '''

        # Character count color
        char_color = 'green'
        if tweet.character_count > 250:
            char_color = 'orange'
        if tweet.character_count > 270:
            char_color = 'red'

        return f'''
        <div class="tweet-wrapper">
            {reply_html}
            <div class="tweet">
                <div class="tweet-header">
                    <div class="profile">
                        <div class="avatar">👤</div>
                        <div class="user-info">
                            <span class="display-name">Your Account</span>
                            <span class="username">@yourhandle</span>
                        </div>
                    </div>
                    <div class="tweet-meta">
                        <span class="position">{tweet.position}/{total_tweets}</span>
                        <span class="char-count" style="color: {char_color}">{tweet.character_count}/275</span>
                    </div>
                </div>
                <div class="tweet-content">
                    {self._format_tweet_text(tweet.text)}
                </div>
                {image_html}
                <div class="tweet-footer">
                    <span class="action">💬 Reply</span>
                    <span class="action">🔄 Retweet</span>
                    <span class="action">❤️ Like</span>
                    <span class="action">📊 View</span>
                </div>
            </div>
        </div>
        '''

    def _generate_cta_html(self, thread: Thread) -> str:
        """Generate HTML for call-to-action.

        Args:
            thread: Thread with CTA

        Returns:
            str: HTML for CTA section
        """
        return f'''
        <div class="cta-section">
            <div class="cta-label">📢 Call to Action</div>
            <div class="cta-text">{self._escape_html(thread.call_to_action)}</div>
        </div>
        '''

    def _format_tweet_text(self, text: str) -> str:
        """Format tweet text with line breaks and links.

        Args:
            text: Raw tweet text

        Returns:
            str: Formatted HTML
        """
        import re

        # First, mark hashtags and mentions BEFORE escaping
        # Use placeholders that won't be affected by HTML escaping
        hashtag_placeholder = "___HASHTAG_START___"
        hashtag_end = "___HASHTAG_END___"
        mention_placeholder = "___MENTION_START___"
        mention_end = "___MENTION_END___"

        # Mark hashtags (but not HTML entities like &#39;)
        text = re.sub(r'(?<!&)(#\w+)', f'{hashtag_placeholder}\\1{hashtag_end}', text)

        # Mark mentions
        text = re.sub(r'(@\w+)', f'{mention_placeholder}\\1{mention_end}', text)

        # Escape HTML
        text = self._escape_html(text)

        # Convert line breaks
        text = text.replace('\n', '<br>')

        # Replace placeholders with actual span tags
        text = text.replace(hashtag_placeholder, '<span class="hashtag">')
        text = text.replace(hashtag_end, '</span>')
        text = text.replace(mention_placeholder, '<span class="mention">')
        text = text.replace(mention_end, '</span>')

        return text

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters.

        Args:
            text: Text to escape

        Returns:
            str: Escaped text
        """
        return (text
                .replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;')
                .replace("'", '&#39;'))

    def _get_css(self) -> str:
        """Get CSS styles for the preview.

        Returns:
            str: CSS content
        """
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: linear-gradient(to bottom, #f7f9fc 0%, #e8ecf1 100%);
            color: #14171a;
            line-height: 1.5;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            overflow: hidden;
        }

        .header {
            background: linear-gradient(135deg, #1da1f2 0%, #0d8bd9 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }

        .header h1 {
            font-size: 28px;
            margin-bottom: 15px;
        }

        .stats {
            display: flex;
            justify-content: center;
            gap: 20px;
            font-size: 14px;
        }

        .stat {
            background: rgba(255,255,255,0.2);
            padding: 5px 12px;
            border-radius: 20px;
        }

        .hook-section {
            background: #f0f8ff;
            border-left: 4px solid #1da1f2;
            padding: 20px;
            margin: 20px;
            border-radius: 8px;
        }

        .hook-label {
            font-weight: bold;
            color: #1da1f2;
            margin-bottom: 10px;
            font-size: 14px;
        }

        .hook-text {
            font-size: 18px;
            font-weight: 500;
            color: #14171a;
        }

        .thread-container {
            padding: 20px;
        }

        .tweet-wrapper {
            position: relative;
            margin-bottom: 0;
        }

        .reply-line {
            position: absolute;
            left: 24px;
            top: -10px;
            width: 2px;
            height: 30px;
            background: #cfd9de;
        }

        .reply-label {
            color: #536471;
            font-size: 13px;
            margin-left: 50px;
            margin-bottom: 8px;
        }

        .tweet {
            border: 1px solid #eff3f4;
            border-radius: 16px;
            padding: 16px;
            margin-bottom: 12px;
            background: white;
            transition: background 0.2s;
        }

        .tweet:hover {
            background: #f7f9f9;
        }

        .tweet-header {
            display: flex;
            justify-content: space-between;
            align-items: start;
            margin-bottom: 8px;
        }

        .profile {
            display: flex;
            gap: 12px;
            align-items: center;
        }

        .avatar {
            width: 48px;
            height: 48px;
            border-radius: 50%;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 24px;
        }

        .user-info {
            display: flex;
            flex-direction: column;
        }

        .display-name {
            font-weight: bold;
            font-size: 15px;
        }

        .username {
            color: #536471;
            font-size: 14px;
        }

        .tweet-meta {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
            gap: 4px;
        }

        .position {
            background: #1da1f2;
            color: white;
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: bold;
        }

        .char-count {
            font-size: 12px;
            font-weight: 500;
        }

        .tweet-content {
            font-size: 15px;
            line-height: 1.5;
            margin: 12px 0;
            color: #14171a;
        }

        .hashtag {
            color: #1da1f2;
            font-weight: 500;
        }

        .mention {
            color: #1da1f2;
            font-weight: 500;
        }

        .tweet-image {
            margin: 12px 0;
            border-radius: 16px;
            overflow: hidden;
            border: 1px solid #eff3f4;
        }

        .tweet-image img {
            width: 100%;
            height: auto;
            display: block;
        }

        .tweet-footer {
            display: flex;
            justify-content: space-around;
            padding-top: 12px;
            border-top: 1px solid #eff3f4;
            margin-top: 12px;
        }

        .action {
            color: #536471;
            font-size: 13px;
            cursor: pointer;
            padding: 4px 8px;
            border-radius: 4px;
            transition: background 0.2s;
        }

        .action:hover {
            background: #f7f9f9;
        }

        .cta-section {
            background: #f0fff4;
            border-left: 4px solid #10b981;
            padding: 20px;
            margin: 20px;
            border-radius: 8px;
        }

        .cta-label {
            font-weight: bold;
            color: #10b981;
            margin-bottom: 10px;
            font-size: 14px;
        }

        .cta-text {
            font-size: 15px;
            color: #14171a;
            font-style: italic;
        }

        .footer {
            background: #f7f9f9;
            padding: 20px;
            text-align: center;
            font-size: 13px;
            color: #536471;
            border-top: 1px solid #eff3f4;
        }

        .footer p {
            margin: 8px 0;
        }

        .source {
            font-family: 'Courier New', monospace;
            font-size: 12px;
        }

        @media (max-width: 600px) {
            body {
                padding: 0;
            }

            .container {
                border-radius: 0;
            }
        }
        """
